language: objective-c
osx_image: xcode8.1
env:
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.1"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6s,OS=9.3"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=8.4"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project Timepiece.xcodeproj -scheme "Timepiece iOS" -sdk iphonesimulator10.1 -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO test | xcpretty -c

