language: objective-c
osx_image: xcode8.1
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project Timepiece.xcodeproj -scheme "Timepiece iOS" -sdk iphonesimulator10.1 -destination "platform=iOS Simulator,name=iPhone 7,OS=10.1" ONLY_ACTIVE_ARCH=NO test | xcpretty -c

